import type { SiteConfig } from "@/types";

export const GLOBAL_CONFIG: SiteConfig = {
  companyName: "ООО «Сиеста Центр»",
  brandName: "Алтай изнутри",
  phone: "+7 (923) 227-94-60",
  commissionRate: "10%",
  filters: {
    forWhom: [
      { label: "с детьми", slug: "with-kids" },
      { label: "вдвоём", slug: "in-couple" },
      { label: "компанией", slug: "company" },
      { label: "корпоратив", slug: "corporate" },
    ],
    districts: [
      { label: "Чемал", slug: "cemal" },
      { label: "Майминский", slug: "mayminsky" },
      { label: "Турочакский", slug: "turouchaksky" },
      { label: "Тогульский", slug: "togulsky" },
      { label: "Барашский", slug: "barashsky" },
    ],
    features: [
      { label: "баня", slug: "banya" },
      { label: "бассейн", slug: "pool" },
      { label: "у воды", slug: "waterfront" },
      { label: "зимой", slug: "winter" },
      { label: "можно с животными", slug: "pets" },
    ],
  },
  manifest: {
    title: "ПОЧЕМУ СИЕСТА?",
    subtitle: "Я не рекламирую базы. Я показываю их изнутри.",
    description: "В сети сотни глянцевых каталогов с купленными отзывами. «Сиеста» устроена иначе. Это не самый большой список Алтая, а единственный, где я лично зашел в каждый дом, проверил шумоизоляцию, залез на крышу и отснял честный 3D-тур.",
    features: [
      "Без рекламной воды — только голые факты и личный опыт",
      "Честный разбор «Кому не подойдёт» в каждой карточке",
      "Официальное бронирование через ООО «Сиеста Центр»"
    ]
  },
  promoTour: {
    title: "Экспедиция Сиеста",
    badge: "Личный контроль",
    description: "Сложный авторский маршрут по Алтаю, собранный полностью из баз, которые я проверил лично. Никаких сюрпризов на месте — вы получите именно тот уровень комфорта, который увидели в туре.",
    image: "/media/promo/expedition.jpg"
  },
  testimonials: [
    {
      quote: "Незабываемые впечатления с видом на Аринкиоску!",
      rating: 5,
      baseName: "«Стиль-Золотое цветение»",
    },
    {
      quote: "Персональный комфорт в деревне под старыми кедрами",
      rating: 5,
      baseName: "«Кедровые огни»",
    },
    {
      quote: "Где вы можете отдохнуть от повседневности",
      rating: 5,
      baseName: "«Усадьба Длинная дорога»",
    },
  ],
  objects: [
    {
      slug: "usadba-velvet",
      name: "Усадьба Вельвет",
      type: "усадьба",
      verification: "shot",
      verification_date: "2026-07-14",
      consent: { signed: true, date: "2026-08-15" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Усть-Сема",
        coords: [51.0, 85.9],
        distance_gorno_altaysk_km: 55,
        distance_novosibirsk_km: 510,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "/tours/usadba-velvet/index.html",
        preview: "/media/usadba-velvet/tour-preview.jpg",
        scenes_count: 8,
      },
      photos: [
        {
          src: "/media/usadba-velvet/01.jpg",
          alt: "Вид на террасу усадьбы Вельвет",
          caption: "Терраса у реки",
        },
        {
          src: "/media/usadba-velvet/02.jpg",
          alt: "Интерьер номера",
          caption: "Спальня из кедра",
        },
      ],
      price: {
        from: 2500,
        unit: "чел./сутки",
        included: ["Пользование мангалом", "Парковка"],
        extra: ["Дрова для бани"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "31 декабря – 8 января"],
      },
      capacity: { min: 2, max: 6, units_count: 3 },
      amenities: {
        banya: true,
        pool: true,
        wifi: true,
        kitchen: false,
        heating: true,
        parking: true,
        waterfront: true,
        food: "Завтрак включен",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "low",
          note: "Неодобряемый уровень спален для маленьких детей. Высокие скалы у берега, большие расстояния и открытые проходы между номерами без ограждений.",
        },
        couples: {
          fit: "high",
          note: "Идеальная приватная атмосфера для двоих.",
        },
        company: { fit: "medium", note: "Подходит для спокойных компаний." },
        corporate: {
          fit: "low",
          note: "Малая вместимость для крупных корпоративов.",
        },
      },
      author: {
        verdict:
          "База подкупает своей приватностью и качеством отделки из кедра. Отличный вариант, если вы ищете тишину.",
        good_for: ["Пары", "Любители уединенного отдыха"],
        not_for: ["Семьи с детьми до 5 лет", "Шумные компании"],
        honest_note:
          "Я провел здесь два дня. Сервис ненавязчивый, но учитывайте ограничения по безопасности для детей.",
      },
      booking: {
        min_nights: 1,
        min_nights_high_season: 2,
        prepayment: "30%",
      },
      seo: {
        title: "Усадьба Вельвет — Честный обзор",
        description: "Вся правда об усадьбе Вельвет на Алтае.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
    {
      slug: "glamping-vozduh",
      name: "Глэмпинг «Воздух»",
      type: "глэмпинг",
      verification: "shot",
      verification_date: "2026-07-01",
      consent: { signed: true, date: "2026-07-20" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Узнезя",
        coords: [51.45, 86.05],
        distance_gorno_altaysk_km: 90,
        distance_novosibirsk_km: 530,
        road: "Чемальский тракт",
        winter_access: false,
      },
      tour: {
        url: "/tours/glamping-vozduh/index.html",
        preview: "/media/glamping-vozduh/tour-preview.jpg",
        scenes_count: 5,
      },
      photos: [
        {
          src: "/media/glamping-vozduh/01.jpg",
          alt: "Терраса глэмпинга Воздух",
          caption: "Вид на Катунь",
        },
        {
          src: "/media/glamping-vozduh/02.jpg",
          alt: "Купол глэмпинга Воздух",
          caption: "Номер",
        },
      ],
      price: {
        from: 29000,
        unit: "сут",
        included: ["Завтрак", "Парковка"],
        extra: ["Баня"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август"],
      },
      capacity: { min: 2, max: 4, units_count: 4 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: false,
        heating: false,
        parking: true,
        waterfront: true,
        food: "Завтрак включен",
        pets: false,
        year_round: false,
      },
      suitability: {
        family_kids: {
          fit: "low",
          note: "Нет тепла, стук рок-музыки с соседних площадок, крутой рельеф без детских ограждений — отдых с детьми здесь затруднён.",
        },
        couples: {
          fit: "high",
          note: "Сильный вид и атмосфера для двоих.",
        },
        company: {
          fit: "medium",
          note: "Подходит для небольших взрослых компаний.",
        },
        corporate: { fit: "low", note: "Малая вместимость." },
      },
      author: {
        verdict:
          "Премиальный глэмпинг с сильным видом. Честно: место для взрослых, а не для семей с детьми.",
        good_for: ["Пары", "Взрослые компании"],
        not_for: ["Семьи с детьми", "Кто ищет тишину ночью"],
        honest_note:
          "Красиво, но шумно по вечерам и без нормального отопления в межсезонье.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "30%",
      },
      seo: {
        title: "Глэмпинг «Воздух» — честный обзор",
        description: "Глэмпинг Воздух на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
    {
      slug: "kedrovyj-ogon",
      name: "Кедровый огонь",
      type: "глэмпинг",
      verification: "shot",
      verification_date: "2026-06-20",
      consent: { signed: true, date: "2026-07-01" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Чемал",
        coords: [51.4, 86.0],
        distance_gorno_altaysk_km: 95,
        distance_novosibirsk_km: 540,
        road: "Чемальский тракт",
        winter_access: true,
      },
      tour: {
        url: "/tours/kedrovyj-ogon/index.html",
        preview: "/media/kedrovyj-ogon/tour-preview.jpg",
        scenes_count: 6,
      },
      photos: [
        {
          src: "/media/kedrovyj-ogon/01.jpg",
          alt: "Купол глэмпинга Кедровый огонь",
          caption: "Геодезический купол",
        },
        {
          src: "/media/kedrovyj-ogon/02.jpg",
          alt: "Вечер у костра",
          caption: "Зона отдыха",
        },
      ],
      price: {
        from: 12000,
        unit: "ночь",
        included: ["Завтрак", "Парковка"],
        extra: ["Баня"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август"],
      },
      capacity: { min: 2, max: 4, units_count: 5 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Завтрак включен",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: { fit: "medium", note: "Подходит для спокойных семей." },
        couples: { fit: "high", note: "Романтичная атмосфера купола." },
        company: { fit: "medium", note: "Несколько куполов рядом." },
        corporate: { fit: "low", note: "Малая вместимость." },
      },
      author: {
        verdict:
          "Современный глэмпинг с куполами среди кедров. Тихо, атмосферно, с вниманием к деталям.",
        good_for: ["Пары", "Любители глэмпинга"],
        not_for: ["Крупные компании"],
        honest_note: "Дорога грунтовая — в дождь лучше полный привод.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "30%",
      },
      seo: {
        title: "Кедровый огонь — честный обзор",
        description: "Глэмпинг Кедровый огонь на Алтае.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
    {
      slug: "zolotoe-cvetenie",
      name: "Золотое цветение",
      type: "отель",
      verification: "shot",
      verification_date: "2026-05-12",
      consent: { signed: true, date: "2026-06-01" },
      location: {
        region: "Республика Алтай",
        district: "Майминский район",
        settlement: "село Манжерок",
        coords: [51.8, 85.8],
        distance_gorno_altaysk_km: 35,
        distance_novosibirsk_km: 480,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "/tours/zolotoe-cvetenie/index.html",
        preview: "/media/zolotoe-cvetenie/tour-preview.jpg",
        scenes_count: 4,
      },
      photos: [
        {
          src: "/media/zolotoe-cvetenie/01.jpg",
          alt: "Интерьер Золотое цветение",
          caption: "Панорамный номер",
        },
        {
          src: "/media/zolotoe-cvetenie/02.jpg",
          alt: "Вид из окна",
          caption: "Горы на рассвете",
        },
      ],
      price: {
        from: 16000,
        unit: "ночь",
        included: ["Завтрак", "Wi-Fi", "Парковка"],
        extra: ["СПА"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "новогодние праздники"],
      },
      capacity: { min: 2, max: 3, units_count: 12 },
      amenities: {
        banya: true,
        pool: true,
        wifi: true,
        kitchen: false,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Ресторан на территории",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: { fit: "high", note: "Удобно для семей с детьми." },
        couples: { fit: "high", note: "Панорамные окна и тихие номера." },
        company: { fit: "medium", note: "Подходит небольшим группам." },
        corporate: { fit: "medium", note: "Есть зал для встреч." },
      },
      author: {
        verdict:
          "Дизайн-отель с панорамными видами. Чистый сервис и продуманные интерьеры.",
        good_for: ["Пары", "Семьи"],
        not_for: ["Кто ищет полное уединение в лесу"],
        honest_note:
          "Рядом курортная инфраструктура — вечерами бывает оживлённее.",
      },
      booking: {
        min_nights: 1,
        min_nights_high_season: 2,
        prepayment: "50%",
      },
      seo: {
        title: "Золотое цветение — честный обзор",
        description: "Отель Золотое цветение на Алтае.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
  ],
};
