import type { SiteConfig } from "@/types";

export const GLOBAL_CONFIG: SiteConfig = {
  companyName: "ООО «Сиеста Центр»",
  brandName: "Алтай изнутри",
  phone: "+7 (923) 227-94-60",
  commissionRate: "10%",
  filters: {
    forWhom: [
      { label: "с детьми", slug: "with-kids" },
      { label: "вдвоём", slug: "in-couple" },
      { label: "компанией", slug: "company" },
      { label: "корпоратив", slug: "corporate" },
    ],
    districts: [
      { label: "Чемал", slug: "cemal" },
      { label: "Майминский", slug: "mayminsky" },
      { label: "Турочакский", slug: "turouchaksky" },
      { label: "Тогульский", slug: "togulsky" },
      { label: "Барашский", slug: "barashsky" },
    ],
    features: [
      { label: "баня", slug: "banya" },
      { label: "бассейн", slug: "pool" },
      { label: "у воды", slug: "waterfront" },
      { label: "зимой", slug: "winter" },
      { label: "можно с животными", slug: "pets" },
    ],
  },
  manifest: {
    title: "ПОЧЕМУ СИЕСТА?",
    subtitle: "Я не рекламирую базы. Я показываю их изнутри.",
    description:
      "В сети сотни глянцевых каталогов с купленными отзывами. «Сиеста» устроена иначе. Это не самый большой список Алтая, а единственный, где я лично зашел в каждый дом, проверил шумоизоляцию, залез на крышу и отснял честный 3D-тур.",
    features: [
      "Без рекламной воды — только голые факты и личный опыт",
      "Честный разбор «Кому не подойдёт» в каждой карточке",
      "Официальное бронирование через ООО «Сиеста Центр»",
    ],
  },
  promoTour: {
    title: "Каталог Сиеста",
    badge: "Личный контроль",
    description:
      "Каталог полностью собран из баз, которые мы проверили лично. Никаких сюрпризов на месте — вы получите именно тот уровень комфорта, который увидели в каталоге.",
    image: "/media/promo/expedition.jpg",
  },
  testimonials: [
    {
      quote: "Незабываемые впечатления с видом на Аринкиоску!",
      rating: 5,
      baseName: "«Парк-отель Скала»",
    },
    {
      quote: "Персональный комфорт в деревне под старыми кедрами",
      rating: 5,
      baseName: "«Усадьба Кругловых»",
    },
    {
      quote: "Где вы можете отдохнуть от повседневности",
      rating: 5,
      baseName: "«Эко-отель Гринландия»",
    },
  ],
  objects: [
    {
      slug: "usadba-velvet",
      name: "Усадьба Вельвет",
      type: "усадьба",
      verification: "shot",
      verification_date: "2026-07-14",
      consent: { signed: true, date: "2026-08-15" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Усть-Сема",
        coords: [51.0, 85.9],
        distance_gorno_altaysk_km: 55,
        distance_novosibirsk_km: 510,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/usadba-velvet/tour-preview.jpg",
        scenes_count: 8,
      },
      photos: [
        {
          src: "/media/usadba-velvet/01.jpg",
          alt: "Вид на террасу усадьбы Вельвет",
          caption: "Терраса у реки",
        },
        {
          src: "/media/usadba-velvet/02.jpg",
          alt: "Интерьер номера",
          caption: "Спальня из кедра",
        },
      ],
      price: {
        from: 2500,
        unit: "чел./сутки",
        included: ["Пользование мангалом", "Парковка"],
        extra: ["Дрова для бани"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "31 декабря – 8 января"],
      },
      capacity: { min: 2, max: 6, units_count: 3 },
      amenities: {
        banya: true,
        pool: true,
        wifi: true,
        kitchen: false,
        heating: true,
        parking: true,
        waterfront: true,
        food: "Завтрак включен",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "low",
          note: "Неодобряемый уровень спален для маленьких детей. Высокие скалы у берега, большие расстояния и открытые проходы между номерами без ограждений.",
        },
        couples: {
          fit: "high",
          note: "Идеальная приватная атмосфера для двоих.",
        },
        company: { fit: "medium", note: "Подходит для спокойных компаний." },
        corporate: {
          fit: "low",
          note: "Малая вместимость для крупных корпоративов.",
        },
      },
      author: {
        verdict:
          "База подкупает своей приватностью и качеством отделки из кедра. Отличный вариант, если вы ищете тишину.",
        good_for: ["Пары", "Любители уединенного отдыха"],
        not_for: ["Семьи с детьми до 5 лет", "Шумные компании"],
        honest_note:
          "Я провел здесь два дня. Сервис ненавязчивый, но учитывайте ограничения по безопасности для детей.",
      },
      booking: {
        min_nights: 1,
        min_nights_high_season: 2,
        prepayment: "30%",
      },
      seo: {
        title: "Усадьба Вельвет — Честный обзор",
        description: "Вся правда об усадьбе Вельвет на Алтае.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
    {
      slug: "glamping-vozduh",
      name: "Глэмпинг «Воздух»",
      type: "глэмпинг",
      verification: "shot",
      verification_date: "2026-07-01",
      consent: { signed: true, date: "2026-07-20" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Узнезя",
        coords: [51.45, 86.05],
        distance_gorno_altaysk_km: 90,
        distance_novosibirsk_km: 530,
        road: "Чемальский тракт",
        winter_access: false,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/glamping-vozduh/tour-preview.jpg",
        scenes_count: 5,
      },
      photos: [
        {
          src: "/media/glamping-vozduh/01.jpg",
          alt: "Терраса глэмпинга Воздух",
          caption: "Вид на Катунь",
        },
        {
          src: "/media/glamping-vozduh/02.jpg",
          alt: "Купол глэмпинга Воздух",
          caption: "Номер",
        },
      ],
      price: {
        from: 29000,
        unit: "сут",
        included: ["Завтрак", "Парковка"],
        extra: ["Баня"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август"],
      },
      capacity: { min: 2, max: 4, units_count: 4 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: false,
        heating: false,
        parking: true,
        waterfront: true,
        food: "Завтрак включен",
        pets: false,
        year_round: false,
      },
      suitability: {
        family_kids: {
          fit: "low",
          note: "Нет тепла, стук рок-музыки с соседних площадок, крутой рельеф без детских ограждений — отдых с детьми здесь затруднён.",
        },
        couples: {
          fit: "high",
          note: "Сильный вид и атмосфера для двоих.",
        },
        company: {
          fit: "medium",
          note: "Подходит для небольших взрослых компаний.",
        },
        corporate: { fit: "low", note: "Малая вместимость." },
      },
      author: {
        verdict:
          "Премиальный глэмпинг с сильным видом. Честно: место для взрослых, а не для семей с детьми.",
        good_for: ["Пары", "Взрослые компании"],
        not_for: ["Семьи с детьми", "Кто ищет тишину ночью"],
        honest_note:
          "Красиво, но шумно по вечерам и без нормального отопления в межсезонье.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "30%",
      },
      seo: {
        title: "Глэмпинг «Воздух» — честный обзор",
        description: "Глэмпинг Воздух на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-10",
    },
    {
      slug: "park-otel-skala",
      name: "Парк-отель «Скала»",
      type: "парк-отель",
      verification: "shot",
      verification_date: "2026-06-18",
      consent: { signed: true, date: "2026-07-02" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "село Элекмонар",
        coords: [51.47, 86.0],
        distance_gorno_altaysk_km: 85,
        distance_novosibirsk_km: 525,
        road: "Чемальский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/park-otel-skala/tour-preview.jpg",
        scenes_count: 7,
      },
      photos: [
        {
          src: "/media/park-otel-skala/01.jpg",
          alt: "A-frame домики парк-отеля Скала",
          caption: "Домики на лугу",
        },
      ],
      price: {
        from: 14500,
        unit: "ночь",
        included: ["Завтрак", "Парковка", "Wi-Fi"],
        extra: ["Баня", "Трансфер"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "новогодние праздники"],
      },
      capacity: { min: 2, max: 4, units_count: 8 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Завтрак включен",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "medium",
          note: "Территория открытая, рядом склон — детям нужен постоянный контроль.",
        },
        couples: {
          fit: "high",
          note: "Панорамные окна и вид на хребет — сильный романтический сценарий.",
        },
        company: { fit: "high", note: "Несколько домиков рядом, удобно компаниям." },
        corporate: {
          fit: "medium",
          note: "Можно собрать небольшую группу, но нет большого зала.",
        },
      },
      author: {
        verdict:
          "Современные A-frame домики на фоне скал. Вид сильный, сервис аккуратный, без лишней показной роскоши.",
        good_for: ["Пары", "Небольшие компании", "Фотографы"],
        not_for: ["Кто боится ветра на открытом склоне"],
        honest_note:
          "Вечером на склоне ощутимо холоднее, чем в долине — берите тёплые вещи даже летом.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "40%",
      },
      seo: {
        title: "Парк-отель «Скала» — честный обзор",
        description: "Парк-отель Скала на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "usadba-kruglovyh",
      name: "Усадьба Кругловых",
      type: "усадьба",
      verification: "shot",
      verification_date: "2026-05-28",
      consent: { signed: true, date: "2026-06-15" },
      location: {
        region: "Республика Алтай",
        district: "Майминский район",
        settlement: "село Соузга",
        coords: [51.75, 85.85],
        distance_gorno_altaysk_km: 28,
        distance_novosibirsk_km: 470,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/usadba-kruglovyh/tour-preview.jpg",
        scenes_count: 6,
      },
      photos: [
        {
          src: "/media/usadba-kruglovyh/01.jpg",
          alt: "Территория усадьбы Кругловых",
          caption: "Деревянные коттеджи",
        },
      ],
      price: {
        from: 8500,
        unit: "ночь",
        included: ["Парковка", "Мангал", "Детская площадка"],
        extra: ["Баня", "Питание"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август"],
      },
      capacity: { min: 2, max: 8, units_count: 5 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Кухня в доме",
        pets: true,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "high",
          note: "Есть площадка и ровная территория — семьям с детьми здесь комфортно.",
        },
        couples: {
          fit: "medium",
          note: "Уютно, но рядом могут быть семьи — полной тишины не ждите.",
        },
        company: { fit: "high", note: "Несколько домов, удобно большим компаниям." },
        corporate: {
          fit: "medium",
          note: "Подойдёт для небольшого выезда без строгой деловой программы.",
        },
      },
      author: {
        verdict:
          "Семейная усадьба с ухоженным двором и понятным сервисом. Без вау-эффекта, но честно и тепло.",
        good_for: ["Семьи", "Компании друзей"],
        not_for: ["Кто ищет премиальный дизайн-отель"],
        honest_note:
          "Дома добротные, но мебель разного возраста — это жилая усадьба, а не глянцевый курорт.",
      },
      booking: {
        min_nights: 1,
        min_nights_high_season: 2,
        prepayment: "30%",
      },
      seo: {
        title: "Усадьба Кругловых — честный обзор",
        description: "Усадьба Кругловых на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "eko-otel-grinlandiya",
      name: "Эко-отель «Гринландия»",
      type: "эко-отель",
      verification: "shot",
      verification_date: "2026-04-22",
      consent: { signed: true, date: "2026-05-10" },
      location: {
        region: "Республика Алтай",
        district: "Турочакский район",
        settlement: "село Артыбаш",
        coords: [51.79, 87.25],
        distance_gorno_altaysk_km: 160,
        distance_novosibirsk_km: 580,
        road: "Чемал — Артыбаш",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/eko-otel-grinlandiya/tour-preview.jpg",
        scenes_count: 9,
      },
      photos: [
        {
          src: "/media/eko-otel-grinlandiya/01.jpg",
          alt: "Зимний вид эко-отеля Гринландия",
          caption: "A-frame ночью",
        },
      ],
      price: {
        from: 18000,
        unit: "ночь",
        included: ["Завтрак", "Wi-Fi", "Парковка"],
        extra: ["Ужин", "Сауна"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июль", "август", "новогодние праздники"],
      },
      capacity: { min: 2, max: 4, units_count: 10 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: false,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Завтрак и ужин по меню",
        pets: false,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "medium",
          note: "Зимой скользкие дорожки — с малышами нужна осторожность.",
        },
        couples: {
          fit: "high",
          note: "Тёплый свет, панорама и тишина — сильный формат для двоих.",
        },
        company: { fit: "medium", note: "Домики разнесены, компаниям придётся гулять." },
        corporate: { fit: "low", note: "Нет инфраструктуры под деловые встречи." },
      },
      author: {
        verdict:
          "Аккуратный эко-отель с сильной атмосферой зимой. Дороговато, но вид и тепло внутри отрабатывают цену.",
        good_for: ["Пары", "Зимний отдых"],
        not_for: ["Кто хочет шумную анимацию"],
        honest_note:
          "Дорога до Артыбаша длинная. Если едете на 1 ночь — усталость от трансфера может съесть впечатление.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "50%",
      },
      seo: {
        title: "Эко-отель «Гринландия» — честный обзор",
        description: "Эко-отель Гринландия на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "usadba-sokol",
      name: "Усадьба «Сокол»",
      type: "усадьба",
      verification: "shot",
      verification_date: "2026-03-15",
      consent: { signed: true, date: "2026-04-01" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "село Чемал",
        coords: [51.41, 86.0],
        distance_gorno_altaysk_km: 100,
        distance_novosibirsk_km: 545,
        road: "Чемальский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/usadba-sokol/tour-preview.jpg",
        scenes_count: 5,
      },
      photos: [
        {
          src: "/media/usadba-sokol/01.jpg",
          alt: "Сруб усадьбы Сокол зимой",
          caption: "Дом у скал",
        },
      ],
      price: {
        from: 11000,
        unit: "ночь",
        included: ["Парковка", "Баня 1 час"],
        extra: ["Доп. час бани", "Питание"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "новогодние праздники"],
      },
      capacity: { min: 2, max: 10, units_count: 2 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Самостоятельно",
        pets: true,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "medium",
          note: "Большой дом удобен, но рядом крутой рельеф без сетки.",
        },
        couples: {
          fit: "medium",
          note: "Формат скорее под семью или компанию, чем под двоих.",
        },
        company: { fit: "high", note: "Два дома — комфортно на 8–10 человек." },
        corporate: { fit: "low", note: "Нет переговорной и стабильного интернета для созвонов." },
      },
      author: {
        verdict:
          "Массивный сруб у скал. Зимой выглядит мощно, летом — как классическая алтайская усадьба без лишнего пафоса.",
        good_for: ["Компании", "Семьи побольше"],
        not_for: ["Кто хочет отельный сервис all inclusive"],
        honest_note:
          "Хозяева отзывчивые, но всё «по-домашнему»: уточняйте мелочи заранее, а не по приезду.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "30%",
      },
      seo: {
        title: "Усадьба «Сокол» — честный обзор",
        description: "Усадьба Сокол на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "turbaza-tihiy-bereg",
      name: "Турбаза «Тихий Берег»",
      type: "турбаза",
      verification: "shot",
      verification_date: "2026-06-05",
      consent: { signed: true, date: "2026-06-20" },
      location: {
        region: "Республика Алтай",
        district: "Чемальский район",
        settlement: "посёлок Чепош",
        coords: [51.52, 85.95],
        distance_gorno_altaysk_km: 70,
        distance_novosibirsk_km: 515,
        road: "Чуйский тракт",
        winter_access: false,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/turbaza-tihiy-bereg/tour-preview.jpg",
        scenes_count: 4,
      },
      photos: [
        {
          src: "/media/turbaza-tihiy-bereg/01.jpg",
          alt: "Бассейн турбазы Тихий Берег",
          caption: "Бассейн и домики",
        },
      ],
      price: {
        from: 6500,
        unit: "ночь",
        included: ["Парковка", "Пользование бассейном"],
        extra: ["Баня", "Завтрак"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июнь", "июль", "август"],
      },
      capacity: { min: 2, max: 5, units_count: 12 },
      amenities: {
        banya: true,
        pool: true,
        wifi: true,
        kitchen: true,
        heating: false,
        parking: true,
        waterfront: false,
        food: "Кафе на территории",
        pets: false,
        year_round: false,
      },
      suitability: {
        family_kids: {
          fit: "high",
          note: "Бассейн и ровная территория — детям здесь обычно нравится.",
        },
        couples: {
          fit: "medium",
          note: "Летом шумно у воды, для романтики лучше вечер после 21:00.",
        },
        company: { fit: "high", note: "Много домиков, легко разместить компанию." },
        corporate: {
          fit: "medium",
          note: "Можно собрать тимбилдинг летом, зимой база закрыта.",
        },
      },
      author: {
        verdict:
          "Летняя турбаза с бассейном и понятной инфраструктурой. Не премиум, но для семейного заезда работает.",
        good_for: ["Семьи", "Компании летом"],
        not_for: ["Зимний отдых", "Кто ищет тишину утром"],
        honest_note:
          "Название «Тихий» — маркетинг. В пик сезона у бассейна бывает людно и громко.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "30%",
      },
      seo: {
        title: "Турбаза «Тихий Берег» — честный обзор",
        description: "Турбаза Тихий Берег на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "turbaza-altair",
      name: "Турбаза «Алтаир»",
      type: "турбаза",
      verification: "shot",
      verification_date: "2026-05-02",
      consent: { signed: true, date: "2026-05-18" },
      location: {
        region: "Республика Алтай",
        district: "Онгудайский район",
        settlement: "село Хабаровка",
        coords: [50.75, 86.1],
        distance_gorno_altaysk_km: 210,
        distance_novosibirsk_km: 650,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/turbaza-altair/tour-preview.jpg",
        scenes_count: 3,
      },
      photos: [
        {
          src: "/media/turbaza-altair/01.jpg",
          alt: "Территория турбазы Алтаир",
          caption: "Домики у гор",
        },
      ],
      price: {
        from: 4800,
        unit: "ночь",
        included: ["Парковка", "Мангал"],
        extra: ["Баня", "Питание"],
        note: "Цена ориентировочная, уточняется при заявке.",
        high_season: ["июль", "август"],
      },
      capacity: { min: 2, max: 6, units_count: 9 },
      amenities: {
        banya: true,
        pool: false,
        wifi: false,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Самостоятельно / по договорённости",
        pets: true,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "medium",
          note: "Простая база без анимации — детям может быть скучно после дня прогулок.",
        },
        couples: {
          fit: "high",
          note: "Удалённость и звёздное небо — хороший формат для двоих.",
        },
        company: { fit: "high", note: "Недорого и вместительно для компаний." },
        corporate: { fit: "low", note: "Слабый интернет и нет зала." },
      },
      author: {
        verdict:
          "Бюджетная точка на Чуйском тракте. Без глянца, зато честная цена и нормальная баня.",
        good_for: ["Автопутешественники", "Компании"],
        not_for: ["Кто ждёт ресторан и SPA"],
        honest_note:
          "Связь ловит через раз. Скачайте офлайн-карты заранее.",
      },
      booking: {
        min_nights: 1,
        min_nights_high_season: 2,
        prepayment: "20%",
      },
      seo: {
        title: "Турбаза «Алтаир» — честный обзор",
        description: "Турбаза Алтаир на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
    {
      slug: "kottedzh-ust-muny",
      name: "Коттедж в Усть-Муны",
      type: "коттедж",
      verification: "shot",
      verification_date: "2026-07-08",
      consent: { signed: true, date: "2026-07-25" },
      location: {
        region: "Республика Алтай",
        district: "Майминский район",
        settlement: "село Усть-Муны",
        coords: [51.72, 85.78],
        distance_gorno_altaysk_km: 40,
        distance_novosibirsk_km: 490,
        road: "Чуйский тракт",
        winter_access: true,
      },
      tour: {
        url: "https://tridetur.ru/360/vozduh_3d/",
        preview: "/media/kottedzh-ust-muny/tour-preview.jpg",
        scenes_count: 4,
      },
      photos: [
        {
          src: "/media/kottedzh-ust-muny/01.jpg",
          alt: "Коттедж в Усть-Муны зимой",
          caption: "Сруб у гор",
        },
      ],
      price: {
        from: 9500,
        unit: "ночь",
        included: ["Вся кухня", "Парковка", "Постельное бельё"],
        extra: ["Баня", "Уборка"],
        note: "Цена за весь дом, уточняется при заявке.",
        high_season: ["июнь", "июль", "август", "новогодние праздники"],
      },
      capacity: { min: 2, max: 7, units_count: 1 },
      amenities: {
        banya: true,
        pool: false,
        wifi: true,
        kitchen: true,
        heating: true,
        parking: true,
        waterfront: false,
        food: "Самостоятельно",
        pets: true,
        year_round: true,
      },
      suitability: {
        family_kids: {
          fit: "high",
          note: "Один дом на семью — удобно, двор закрытый.",
        },
        couples: {
          fit: "medium",
          note: "Для двоих дом великоват, но тихо и автономно.",
        },
        company: { fit: "high", note: "Идеально снять целиком на компанию друзей." },
        corporate: { fit: "low", note: "Один объект — не формат под корпоратив." },
      },
      author: {
        verdict:
          "Отдельный коттедж без соседей за стенкой. Хороший вариант, если хотите жить «как дома», но с видом на Алтай.",
        good_for: ["Семьи", "Компании до 7 человек"],
        not_for: ["Кто хочет ресепшен и ежедневную уборку"],
        honest_note:
          "Это аренда дома, а не отель: мусор, посуда и порядок — на вас.",
      },
      booking: {
        min_nights: 2,
        min_nights_high_season: 3,
        prepayment: "40%",
      },
      seo: {
        title: "Коттедж в Усть-Муны — честный обзор",
        description: "Коттедж в Усть-Муны на Алтае: плюсы и ограничения.",
        og_image: "",
      },
      status: "published",
      updated_at: "2026-08-11",
    },
  ],
};
