export const UI_CONFIG = {
  home: {
    heroTitle: "Алтай изнутри",
    chooseLocation: "В каталог",
    catalogTitle: "Каталог баз отдыха",
    catalogHref: "/catalog",
    bookCta: "Забронировать",
    tourBadge: "3D-тур",
    cultureTitle: "Что ждёт вас на базах отдыха?",
    cultureMore: "Подробнее ›",
    thumbAltFallback: "Локация на Алтае",
    heroImage: "/media/hero/home.webp",
    scrollDownAria: "Прокрутить вниз",
    phoneCopied: "Скопировано",
    featuredSlugs: ["park-otel-skala", "usadba-kruglovyh"] as const,
  },
  filters: {
    forWhom: "Для кого",
    district: "Район",
    features: "Фишки",
    price: "Цена",
    viewMode: "Список / Карта",
    list: "Список",
    map: "Карта",
  },
  catalog: {
    monogram: "АИ",
    notForLabel: "Кому не подойдёт:",
    empty: "По выбранным фильтрам ничего не найдено",
    mapImage: "/media/catalog-map.png",
    mapAlt: "Карта баз отдыха",
    backToHome: "← На главную",
  },
  detailPage: {
    backToCatalog: "← К каталогу объектов",
  },
  base: {
    notSuitableTitle: "КОМУ НЕ ПОДОЙДЁТ",
    bookingTitle: "Оставить заявку",
    submitCta: "Оставить заявку",
    bookingNotePrefix: "Ваша заявка будет отправлена менеджеру",
    bookCta: "Забронировать",
    enter360: "360° Зайти внутрь",
    expandFullscreen: "Развернуть",
    exitFullscreen: "Свернуть",
    tourBadge: "3D-тур",
    unitsOne: "домик",
    unitsFew: "домика",
    unitsMany: "домиков",
    guestsLabel: "гостей",
    goodForTitle: "КОМУ ПОДОЙДЁТ",
    honestNoteTitle: "ЧЕСТНО ОТ АВТОРА",
    distanceFromGorno: "км от Горно-Алтайска",
    distanceFromNovosibirsk: "км от Новосибирска",
    pricePrefix: "от",
    morePhotosPrefix: "ещё",
    detailsTitle: "Подробно",
    amenitiesTitle: "Что есть",
    priceTitle: "Сколько стоит",
    aboutCatalog: "В каталог",
    backAria: "Назад",
    placeholders: {
      name: "Имя",
      phone: "Телефон",
      dates: "Даты заезда-выезда",
    },
    amenityLabels: {
      banya: "Баня",
      pool: "Бассейн",
      wifi: "Wi‑Fi",
      kitchen: "Кухня",
      heating: "Отопление",
      parking: "Парковка",
      waterfront: "У воды",
      pets: "С животными",
      year_round: "Круглый год",
    },
    notFoundTitle: "Объект не найден",
    backHome: "На главную",
  },
  common: {
    copyright: "©",
  },
} as const;
