export const UI_CONFIG = {
  /** Пути и подписи навигации — единый источник */
  routing: {
    home: {
      href: "/",
      backLabel: "← На главную",
      label: "На главную",
    },
    catalog: {
      href: "/catalog",
      backLabel: "← К каталогу объектов",
      /** CTA / короткая ссылка «в каталог» */
      ctaLabel: "В каталог",
    },
  },
  common: {
    copyright: "©",
    bookCta: "Забронировать",
    tourBadge: "3D-тур",
  },
  home: {
    heroTitle: "Алтай изнутри",
    catalogTitle: "Каталог баз отдыха",
    cultureTitle: "Что ждёт вас на базах отдыха?",
    cultureMore: "Подробнее ›",
    thumbAltFallback: "Локация на Алтае",
    heroImage: "/media/hero/home.webp",
    scrollDownAria: "Прокрутить вниз",
    phoneCopied: "Скопировано",
    featuredSlugs: ["park-otel-skala", "usadba-kruglovyh"] as const,
  },
  filters: {
    forWhom: "Для кого",
    district: "Район",
    features: "Фишки",
    price: "Цена",
    viewMode: "Список / Карта",
    list: "Список",
    map: "Карта",
  },
  catalog: {
    monogram: "АИ",
    notForLabel: "Кому не подойдёт:",
    empty: "По выбранным фильтрам ничего не найдено",
    emptySubtitle:
      "Попробуйте изменить район, удобства — возможно, подходящая база есть чуть шире по критериям.",
    emptyReset: "Сбросить фильтры",
    mapImage: "/media/catalog-map.png",
    mapAlt: "Карта баз отдыха",
    mapLoading: "Загружаем карту…",
    closeCard: "Закрыть",
  },
  base: {
    notSuitableTitle: "КОМУ НЕ ПОДОЙДЁТ",
    bookingTitle: "Оставить заявку",
    submitCta: "Оставить заявку",
    submittingCta: "Отправляем…",
    bookingNotePrefix: "Ваша заявка будет отправлена менеджеру",
    bookingError: "Не удалось отправить заявку. Попробуйте ещё раз чуть позже.",
    bookingConfigError:
      "Приём заявок временно недоступен. Оставьте заявку позже или напишите через форму, когда она снова заработает.",
    enter360: "360° Зайти внутрь",
    tourLoading: "Загрузка...",
    expandFullscreen: "Развернуть",
    exitFullscreen: "Свернуть",
    unitsOne: "домик",
    unitsFew: "домика",
    unitsMany: "домиков",
    guestsLabel: "гостей",
    goodForTitle: "КОМУ ПОДОЙДЁТ",
    honestNoteTitle: "ЧЕСТНО ОТ АВТОРА",
    distanceFromGorno: "км от Горно-Алтайска",
    distanceFromNovosibirsk: "км от Новосибирска",
    morePhotosPrefix: "ещё",
    detailsTitle: "Подробно",
    amenitiesTitle: "Что есть",
    pricePrefix: "от",
    priceTitle: "Сколько стоит",
    priceNote:
      "Актуальную стоимость уточним при заявке — базы часто меняют цены и акции.",
    priceIncluded: "Включено",
    priceExtra: "Дополнительно",
    placeholders: {
      name: "Имя",
      phone: "Телефон",
      dates: "Даты заезда — выезда",
    },
    nameInput: {
      placeholder: "Имя",
      ariaLabel: "Имя",
      incomplete: "Укажите имя",
      invalid: "Имя: от 2 до 40 букв",
    },
    phoneInput: {
      placeholder: "Номер телефона",
      incomplete: "Введите номер полностью",
      invalid: "Похоже, номер указан неверно",
      ariaLabel: "Номер телефона",
      countryAria: "Выбор страны",
    },
    datePicker: {
      triggerLabel: "Выберите даты",
      selectCheckIn: "Сначала выберите дату заезда",
      selectCheckOut: "Теперь выберите дату выезда",
      nightsOne: "день",
      nightsFew: "дня",
      nightsMany: "дней",
      clear: "Сбросить",
      apply: "Готово",
      weekdays: ["Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс"] as const,
      months: [
        "январь",
        "февраль",
        "март",
        "апрель",
        "май",
        "июнь",
        "июль",
        "август",
        "сентябрь",
        "октябрь",
        "ноябрь",
        "декабрь",
      ] as const,
      monthsShort: [
        "янв",
        "фев",
        "мар",
        "апр",
        "мая",
        "июн",
        "июл",
        "авг",
        "сен",
        "окт",
        "ноя",
        "дек",
      ] as const,
      prevMonth: "Предыдущий месяц",
      nextMonth: "Следующий месяц",
    },
    amenityLabels: {
      banya: "Баня",
      pool: "Бассейн",
      wifi: "Wi‑Fi",
      kitchen: "Кухня",
      heating: "Отопление",
      parking: "Парковка",
      waterfront: "У воды",
      pets: "С животными",
      year_round: "Круглый год",
    },
    notFoundTitle: "Объект не найден",
  },
  spasibo: {
    title: "Заявка принята",
    subtitle: "Спасибо — мы уже смотрим даты и свободные дома.",
    body: "Менеджер ООО «Сиеста Центр» свяжется с вами в ближайшее время и уточнит детали.",
    stepsTitle: "Что дальше",
    steps: [
      "Проверим наличие на ваши даты",
      "Уточним детали, условия заезда и стоимость",
      "Пришлём подтверждение бронирования",
    ] as const,
    catalogCta: "Смотреть каталог",
    homeCta: "На главную",
  },
  politika: {
    title: "Политика конфиденциальности",
    updatedLabel: "Дата обновления",
    updatedAt: "13 августа 2026 г.",
    intro:
      "Настоящая Политика определяет порядок обработки и защиты персональных данных пользователей сайта «Алтай изнутри», принадлежащего ООО «Сиеста Центр».",
    backLabel: "← На главную",
    footerLink: "Политика конфиденциальности",
  },
} as const;
